name: Deploy to Azure Web App

on:
  push:
    branches:
      - master  # Thay đổi thành nhánh mà bạn muốn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: thien.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t thien.azurecr.io/laravel:latest .
        docker push thien.azurecr.io/laravel:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: thien
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: thien.azurecr.io/laravel:latest
