name: Deploy to Azure App Service

on:
  push:
    branches:
      - master  # Thay đổi nếu bạn sử dụng branch khác

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Start docker
      run: docker-compose up -d

